name: Automatically trigger an Action on Pull Request to main

on:
  pull_request:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello
      run: |
        echo "Hello!"
    
