name: Code checks

on:
  workflow_dispatch:
  pull_request:
    branch:
      - main

jobs:
  job1:
    name: linter-testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install Flake8
      run: |
        python -m pip install flake8 pytest
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Install requirements
      run: |
        python3 -m pip install -r requirements.txt
    - name: Run pytest
      run: |
        pytest tests/


