name: Train model in different environments

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Run experiment job
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Trigger Azure Machine Learning job (development)
      run: |
        az ml job create --file src/job.yml --set inputs.data='azureml:diabetes-dev-folder@latest' --stream

  production:
    name: Run production job
    needs: experiment
    runs-on: ubuntu-latest
    environment:
      name: production
      reviewers:
        - Pranjalya
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Trigger Azure Machine Learning job (production)
      run: |
        az ml job create --file src/job.yml --set inputs.data='azureml:diabetes-prod-folder@latest' --stream